# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=14)),
                ('locked_out', models.BooleanField()),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Balances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('balance', models.DecimalField(decimal_places=0, max_digits=16)),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Accounts')),
            ],
            options={
                'db_table': 'balances',
            },
        ),
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_bank', models.DecimalField(decimal_places=0, max_digits=6)),
                ('bank_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'banks',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ident_num', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_currency', models.DecimalField(decimal_places=0, max_digits=3)),
                ('currency_int', models.CharField(max_length=3)),
                ('currency_loc', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docnum', models.CharField(max_length=10)),
                ('dt', models.DateTimeField()),
                ('dt_bank', models.DateTimeField()),
                ('kind', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('purpose', models.TextField()),
                ('amount', models.DecimalField(decimal_places=0, max_digits=16, null=True)),
                ('amount_nv', models.DecimalField(decimal_places=0, max_digits=16, null=True)),
                ('debit_credit', models.BooleanField()),
                ('id_account_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_a', to='mainapp.Accounts')),
                ('id_account_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_b', to='mainapp.Accounts')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('doc_name', models.CharField(max_length=255)),
                ('doc_id_number', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Users_Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_mode', models.BooleanField()),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Accounts')),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Users')),
            ],
            options={
                'db_table': 'users_accounts',
            },
        ),
        migrations.AddField(
            model_name='accounts',
            name='id_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Banks'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Clients'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='id_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Currencies'),
        ),
    ]
